import { ScenarioNotes } from "./ScenarioNotes";
import { useState } from "react";
import { NavLink } from "react-router-dom";
import story from "../../../content/owner-journey.json";
import { LiveFrame, RunView } from "./api";
import { FinancialIllustration, RehearsalEvidence, useExamplePlan } from "./OwnerRooms";

export type RoomKind = "portfolio" | "fleet" | "planner" | "grid" | "anomalies" | "silicon" | "racks" | "dispatch" | "boards" | "lineage" | "yield" | "mcm" | "passport";
export type RoomProps = { run: RunView | null; frames?: LiveFrame[]; playing?: boolean; onPlayRehearsal?: (id:string)=>void; onOpenPracticeFloor?: ()=>void; onOpenTour?: ()=>void; onRehearse?: (id:string)=>void };
const TITLES: Record<RoomKind,string> = { portfolio:"The owner’s review room",fleet:"The facility map",planner:"The design room",grid:"The power room",anomalies:"The evidence and uncertainty room",silicon:"The slow-runner investigation",racks:"The shared cooling investigation",dispatch:"The return-to-service room",boards:"The board investigation",lineage:"The factory-family investigation",yield:"The qualification and evidence room",mcm:"Inside the package",passport:"The equipment history room" };
const CAST: Partial<Record<RoomKind,string>> = {silicon:"silent_straggler",racks:"rack_thermal_shadow",dispatch:"revolving_door",boards:"innocent_chip_dying_board",lineage:"wafer_lot_contagion",yield:"revolving_door",mcm:"fractured_microbump",passport:"cold_plate_torque_fracture"};
const CAMPUSES=[{id:"alpha",name:"Campus Alpha",focus:"Shared power dependencies"},{id:"lone-star",name:"Campus Lone Star",focus:"Compatible spare capacity"},{id:"cascade",name:"Campus Cascade",focus:"Shared cooling dependencies"},{id:"fjord",name:"Campus Fjord",focus:"Checkpoint storage and restore readiness"}];
export function OwnerRoomScreen({kind,run,frames=[],onPlayRehearsal,onOpenPracticeFloor,onOpenTour,onRehearse}:RoomProps & {kind:RoomKind}) {
 const {plan,setPlan,itKw,facilityKw}=useExamplePlan();const [campusId,setCampusId]=useState("alpha");const [topic,setTopic]=useState("capacity");const [record,setRecord]=useState(0);const campus=CAMPUSES.find((c)=>c.id===campusId)!;const character=story.characters.find((c)=>c.id===CAST[kind]);
 return <section className="owner-room"><p><NavLink to="/worksheet">Carry this room’s questions into my facility worksheet</NavLink></p><h1>{TITLES[kind]}</h1>
 {kind==="portfolio"?<><p className="lede">Connect the characters to evidence and operating decisions. The planning example and the rehearsal’s assigned job are different scopes.</p><div className="grid"><article className="panel"><h2>Example facility</h2><p>{plan.chips.toLocaleString()} inventory accelerators; {facilityKw.toFixed(1)} kW illustrative facility power from the shared plan.</p><NavLink to="/planner">Edit the shared plan</NavLink></article><article className="panel"><h2>Current rehearsal</h2><p>{run?.story?.title??"No rehearsal opened"}</p><p>Detailed job: {run?.cluster?.detailed_accelerator_count??"Unknown"}. Useful progress: {run?.metrics?.useful_new?.toFixed(2)??"Unknown"}.</p><p>Other inventory is counted separately, not individually instrumented.</p></article></div><h2>Three different ways work can be lost</h2><div className="owner-paths">{story.characters.filter((c)=>["silent_straggler","rack_thermal_shadow","revolving_door"].includes(c.id)).map((c)=><article className="panel" key={c.id}><h3>{c.name}</h3><p>{c.lesson}</p><p className="muted">{c.coverage}</p>{onPlayRehearsal?<button type="button" onClick={()=>onPlayRehearsal(c.id)}>Rehearse this character</button>:null}</article>)}</div><div className="owner-actions">{onOpenPracticeFloor?<button type="button" onClick={onOpenPracticeFloor}>Open the practice floor</button>:null}{onOpenTour?<button type="button" onClick={onOpenTour}>Open the owner orientation</button>:null}</div></>:null}
 {kind==="fleet"?<><p className="lede">Map fictional sites to their dependencies. Separate campuses are not one globally synchronized training job.</p><label>Example campus<select aria-label="Example campus" value={campusId} onChange={(e)=>setCampusId(e.target.value)}>{CAMPUSES.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><article className="panel"><h2>{campus.name}</h2><p>Review focus: {campus.focus}. For a like-for-like planning illustration, each campus uses the shared plan of {plan.chips.toLocaleString()} accelerators.</p><p>These are fictional site templates, not live inventory. No measured uptime, tariff, demand-response revenue, or cross-campus failover is asserted.</p><p>Ask which workloads can move, where usable checkpoints reside, and which destination has compatible capacity.</p></article><p>The active rehearsal traces {run?.cluster?.detailed_accelerator_count??"an unknown number of"} assigned accelerators. Its results are not multiplied by campus count.</p><NavLink to="/planner">Review shared facility assumptions</NavLink></>:null}
 {kind==="planner"?<><p className="lede">Build an example and take its assumptions to an engineering review. The portfolio, fleet, and power rooms use this same plan.</p><section className="panel"><h2>Shared physical assumptions</h2><p>Initial values are a fictional planning example, not equipment specifications or a design recommendation.</p><div className="owner-inputs">{([["chips","Inventory accelerators"],["watts","Assumed accelerator watts"],["overhead","Additional IT watts per accelerator"],["pue","Assumed facility PUE"]] as const).map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" min={key==="pue"?1:key==="overhead"?0:1} step={key==="chips"?1:"any"} value={plan[key]} onChange={(e)=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=(key==="pue"?1:key==="overhead"?0:1)&&(key!=="chips"||Number.isInteger(n)))setPlan((p)=>({...p,[key]:n}));}}/></label>)}<label>Cooling approach to discuss<select value={plan.cooling} onChange={(e)=>setPlan((p)=>({...p,cooling:e.target.value}))}>{["Direct liquid cooling","Immersion cooling","Rear-door heat exchange","Air cooling"].map((c)=><option key={c}>{c}</option>)}</select></label></div><p>Illustrative IT load: <strong>{itKw.toFixed(1)} kW</strong>. Facility load: <strong>{facilityKw.toFixed(1)} kW</strong>.</p><p>Formula: inventory × (accelerator watts + additional IT watts) ÷ 1,000; facility load = IT load × PUE. PUE is applied once. Choosing a cooling label does not establish a PUE or a safe design.</p></section><section className="panel"><h2>Before committing resources</h2><ul><li>Request power, cooling, network, and storage dependency maps.</li><li>Ask suppliers which specifications, service limits, and records are available.</li><li>Demonstrate restoration and compatible spare use in the chosen runtime.</li><li>Define qualification before launch and after repair.</li></ul><p>Changing this form does not resize the engine rehearsal.</p></section><NavLink to="/grid">Carry the plan into the power room</NavLink></>:null}
 {kind==="grid"?<><p className="lede">Energy use, electrical capacity, and billed demand are different questions.</p><section className="panel"><h2>Your shared planning example</h2><p>{plan.chips.toLocaleString()} inventory accelerators; IT load {itKw.toFixed(1)} kW; facility load {facilityKw.toFixed(1)} kW; PUE {plan.pue}.</p><p>These are the same assumptions as the design room. Facility load already includes PUE.</p></section><label>Question to explore<select value={topic} onChange={(e)=>setTopic(e.target.value)}><option value="capacity">Electrical capacity and transients</option><option value="energy">Energy and electricity bills</option><option value="demand">Demand windows and contract terms</option></select></label><section className="panel"><h2>{topic==="capacity"?"Can the supply tolerate this workload?":topic==="energy"?"What energy does the facility consume?":"How is billed demand measured?"}</h2><p>{topic==="capacity"?"Ask electrical specialists to review capacity, protection, ramps, and shared dependencies. A planning power total does not simulate electrical transients.":topic==="energy"?"Energy is power integrated over time. A bill requires actual tariffs, time-varying operation, and additional charges. Interruption does not necessarily mean all power becomes zero.":"Demand charges depend on the actual measurement window, tariff, and ratchet terms. A short transient and a billed peak are not interchangeable. No generic pacing duration guarantees penalty avoidance."}</p><p>The power-domain rehearsal does not calculate a utility bill.</p></section></>:null}
 {kind==="anomalies"?<><p className="lede">A signal can support an investigation without proving a cause. Missing evidence and “unknown” are legitimate outcomes.</p><section className="panel"><h2>Current operational assessment</h2><p>Leading hypothesis: {run?.hypotheses?.leading_mechanism.replaceAll("_"," ")??"No rehearsal opened"}.</p><p>{run?.hypotheses?.abstain?`Abstaining: ${run.hypotheses.abstain_reason??"insufficient evidence"}`:"Support rankings are not calibrated failure probabilities."}</p><p>The checked trained model lost to its simpler baseline. Rules remain the operational default.</p></section><ScenarioNotes id="silent_subthreshold_cliff"/><section className="panel"><h2>The Whispering Voltage Cliff now has a synthetic margin rehearsal</h2><p>A declared timing-margin relationship can cause validation mismatches and block useful progress. Synthetic pacing has a throughput cost, including a challenge where it is unnecessary. This is not transistor-level prediction, actual weight corruption, or a hardware control. Request independent computation-validation evidence and specialist electrical records.</p></section></>:null}
 {character?<><ScenarioNotes id={character.id}/><p className="lede">{character.scene}</p><p>{character.lesson}</p><p className="muted">{character.coverage}</p>{kind==="dispatch"?<p>Results come from the Python engine. A frontend timer does not grant a pass, and this page does not certify real equipment or dispatch technicians.</p>:null}{onRehearse?<button type="button" onClick={()=>onRehearse(character.id)}>Open the qualification rehearsal</button>:<NavLink className="owner-button" to={`/desk?scenario=${character.id}&chapter=${character.chapter}`}>Select this character’s rehearsal</NavLink>}{run?.story?.id===character.id?<RehearsalEvidence run={run} frames={frames}/>:<p>Run this character to inspect its observed evidence here. Another character’s results are not substituted.</p>}<section className="panel"><h2>Ask your team</h2><p>{character.question}</p><p>Required evidence: {character.fields.join(", ")}.</p></section></>:null}
 {["boards","lineage","yield","mcm","passport"].includes(kind)&&character?<section className="panel"><h2>What a useful investigation record would contain</h2><p>Explore the evidence requirements below. These are proposed record fields, not measurements from real equipment or a manufacturing test.</p><label>Evidence field<select aria-label="Evidence field" value={Math.min(record,character.fields.length-1)} onChange={(e)=>setRecord(Number(e.target.value))}>{character.fields.map((f,i)=><option key={f} value={i}>{f}</option>)}</select></label><p><strong>{character.fields[Math.min(record,character.fields.length-1)]}</strong>: unknown until your team supplies an applicable record.</p><p>A shared factory or assembly history supports an investigation; it does not establish that every related device is defective. The rehearsals now model distinct link, lot, board, strain, and margin behavior. Their actions remain synthetic; no manufacturer diagnostics, warranty submission, equipment certification, or hardware controls are connected.</p><NavLink to="/data">Explore the proposed data catalog</NavLink></section>:null}
 {["portfolio","fleet","planner","grid","anomalies","boards","lineage","yield","mcm","passport"].includes(kind)?<FinancialIllustration/>:null}<div className="owner-actions"><NavLink to="/journey">Return to the owner’s story</NavLink><button type="button" onClick={()=>window.print()}>Print this review</button></div>
 </section>;
}
